### ISSUE TITLE
Working of search feature in Sheet tab

### ISSUE THREAD

**Issue by navjot369** [animeshchaudhri/dsaatlas#6]
The Search feature in sheet tab can work by calling `filter` method before calling `map` method on `sheetData`

<img width="891" alt="Screenshot 2024-05-19 at 5 48 06 PM" src="https://github.com/animeshchaudhri/dsaatlas/assets/109858950/6c1497a3-a514-4836-af3a-055310aeabff">

**Comment by animeshchaudhri** [comment]
go ahead @navjot369
